# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
- gitlab-test
- yaml-lint
- ansible-lint
- tool-test

variables:
  PIPELINE_SCENARIO_NAME: "cicd-debian-11"

###############################################################################
#################### actions
###############################################################################

# To start, we need to lint role's files with a YML vision
# Because if one of the files doesn't respect YML conventions,
# we dont need to test rest of the pipeline
.yaml_lint: &yaml_lint
  stage: yaml-lint
  image: $NEXUS_ADDRESS/$DOCKER_IMAGE_YAML_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - yamllint -c ./.yamllint ./tools/$binary/*.yml # Here mains files
  allow_failure: false
  retry: 2

.ansible_lint: &ansible_lint
  stage: ansible-lint
  image: $NEXUS_ADDRESS/$DOCKER_IMAGE_ANSIBLE_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - ansible-lint --config=./.ansible-lint --exclude molecule --exclude tests ./tools/$binary/*.yml
  allow_failure: false
  retry: 2

.tool_test: &tool_test
  stage: tool-test
  image: $NEXUS_ADDRESS/$DOCKER_IMAGE_DOCKER_MOLECULE
  variables:
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: '1'
  before_script:
    - "python3 -m compileall /usr/lib/python3 -qq"
    - "cp ./.ansible.cfg /root/.ansible.cfg"
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
    - "./build"
  script:
    - "cd ./tools/$binary"
    - "./$binary"
  allow_failure: false
  retry: 2

###############################################################################
#################### CI JOBS
###############################################################################

############################################
#### gitlab-test
############################################

# As a GitLab ci, we use the default template :)
sast:
  stage: gitlab-test
include:
- template: Security/SAST.gitlab-ci.yml
  allow_failure: false

############################################
#### yaml-lint
############################################

yaml_lint_bootstrap_playbook:
  <<: *yaml_lint
  variables:
    binary: "bootstrap_playbook"

yaml_lint_bootstrap_role:
  <<: *yaml_lint
  variables:
    binary: "bootstrap_role"

yaml_lint_bootstrap_ssl_files:
  <<: *yaml_lint
  variables:
    binary: "bootstrap_ssl_files"

############################################
#### ansible-lint
############################################

ansible_lint_bootstrap_playbook:
  <<: *ansible_lint
  variables:
    binary: "bootstrap_playbook"
  needs:
    - "yaml_lint_bootstrap_playbook"

ansible_lint_bootstrap_role:
  <<: *ansible_lint
  variables:
    binary: "bootstrap_role"
  needs:
    - "yaml_lint_bootstrap_role"

ansible_lint_bootstrap_ssl_files:
  <<: *ansible_lint
  variables:
    binary: "bootstrap_ssl_files"
  needs:
    - "yaml_lint_bootstrap_ssl_files"

############################################
#### moelcule test
############################################

tool_test_bootstrap_playbook:
  <<: *tool_test
  variables:
    binary: "bootstrap_playbook"
  needs:
    - "ansible_lint_bootstrap_playbook"

tool_test_bootstrap_role:
  <<: *tool_test
  variables:
    binary: "bootstrap_role"
  needs:
    - "ansible_lint_bootstrap_role"

tool_test_bootstrap_ssl_files:
  <<: *tool_test
  variables:
    binary: "bootstrap_ssl_files"
  needs:
    - "ansible_lint_bootstrap_ssl_files"
