#!/bin/bash

# Installation des rôles initiaux
ansible-galaxy install -r requirements.yml -p ./playbooks

# Parcours des dossiers dans ./playbook
for playbook_dir in ./playbooks/*; do
    # Vérification si le dossier est un répertoire
    if [ -d "$playbook_dir" ]; then
    # Changement de répertoire
    pushd "$playbook_dir" >/dev/null

    # Installation des dépendances des rôles dans le dossier en cours
    ansible-galaxy install -r requirements.yml -p ./roles

    # Revenir au répertoire parent
    popd >/dev/null
    fi
done