#!/bin/bash

cd ../..

sudo ansible-playbook -i ./tools/bootstrap_ssl_files/hosts -e "@./tools/bootstrap_ssl_files/input.yml" ./playbooks/playbook.bootstrap_ssl_files/playbook.yml

sudo chmod 777 -R *
